server.port=8082
spring.application.name=prescription-scanner

REPLACE_WITH_YOUR_GROQ_KEY
groq.api.url=https://api.groq.com/openai/v1/chat/completions

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
