spring.application.name=doctor_service
spring.datasource.url=jdbc:mysql://localhost:3306/doctordb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

server.port=8081

aws.accessKey=REPLACE_WITH_YOUR_AWS_ACCESS_KEY
aws.secretKey=REPLACE_WITH_YOUR_AWS_SECRET_KEY
aws.region=ap-south-1
aws.s3.bucket=my-image-bucket-10002
